m=float(input("Enter the marks scored in Math."))
e=float(input("Enter the marks scored in English."))
s=float(input("Enter the marks scored in Science."))
cs=float(input("Enter the marks scored in Computer Science."))
h=float(input("Enter the marks scored in History."))
totalmarks=(m+e+s+cs+h)
average=(totalmarks/5)
print(totalmarks)
print(average)